### ISSUE TITLE
Comprehensive?

### ISSUE THREAD

**Issue by pjebs** [venkatgoud/screenplay-parsers#11]
I was wondering how comprehensive was this at converting fdx to fountain?

**Comment by venkatgoud** [comment]
This definitely won't cover the entire fdx format. I am not even sure if there is a published format for fdx. The cases this covers are in the test spec file.

**Comment by pjebs** [comment]
I as looking at the fdx files in here: https://github.com/rsdoiel/fdx/tree/main/testdata

Do you know why it fails to open `sample-06.fdx`?

**Comment by pjebs** [comment]
My website (https://petersir.com) can open the fountain version of the file successfully but not the fdx version (using your library).

**Comment by venkatgoud** [comment]
I have a test app here : https://venkatgoud.github.io/fdx-to-fountain/ which uses this library.
I have tried loading the file using it and it seems to parse and create a fountain file fine.

**Comment by pjebs** [comment]
Yes I see my mistake. Awesome work!

**Comment by pjebs** [comment]
Did you manage to find a javascript library to parse pdf files?

**Comment by venkatgoud** [comment]
I didn't have a use case so I didn't look for one. But I know Mozilla has pdf.js and there is pdf2json which is built on top of pdf.js.
